name: Continuous Integration
on: [workflow_dispatch]
#  push:
#    branches:
#      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Continuous Integration
    outputs:
      image: ${{ steps.image.outputs.image_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: mvn -B -Drevision=$GITHUB_RUN_NUMBER clean test
      - name: Build Image
        run: mvn -DskipTests -Drevision=$GITHUB_RUN_NUMBER package
      - name: Extract Image Name
        run: |
          echo "IMAGE_NAME=$(mvn help:evaluate -Drevision=$GITHUB_RUN_NUMBER -Dexpression=spring-boot.build-image.imageName -q -DforceStdout)" >> $GITHUB_ENV
      - name: Push Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE_NAME
          docker logout